### ISSUE TITLE
[multi-screen] - unresponsive Latte at 3 screens system

### ISSUE THREAD

**Issue by saltymedic** [psifidotos/Latte-Dock#116]
I've tried installing the latest build and I get a Segmentation fault (core dumped)

About a week ago I was able to have Latte-Dock run. I've tried using the uninstall script and then installed again but with no change. Any ideas what I'm doing wrong?

Running Arch with KDE and everything up to date.

Thanks

Jason

**Comment by psifidotos** [comment]
try to remove from .config directory any previous

- close Latter
- remove any files of Latte in .config directory:
Latte Dock-appletsrc
lattedock-appletsrc exist
- start Latte

**Comment by saltymedic** [comment]
Thanks for the reply. Still not working after trying your suggestion. Here is the output from the install:

`
[jason@alfred Latte-Dock]$ ./install.sh 
-- Found KF5: success (found suitable version "5.30.0", minimum required is "5.26.0") found components:  Plasma PlasmaQuick WindowSystem Declarative I18n CoreAddons XmlGui DBusAddons IconThemes 
CMake Warning (dev) at /usr/lib64/cmake/Qt5/Qt5ModuleLocation.cmake:4 (set):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '${_qt5_install_prefix}/Qt5@module@/Qt5@module@Config.cmake'

  the old evaluation rules produce:

    '/usr/lib64/cmake/Qt5/Qt5Config.cmake'

  but the new evaluation rules produce:

    '/usr/lib64/cmake/Qt5@module@/Qt5@module@Config.cmake'

  Using the old result for compatibility since the policy is not set.
Call Stack (most recent call first):
  /usr/lib64/cmake/Qt5/Qt5Config.cmake:25 (include)
  app/CMakeLists.txt:1 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could not set up the appstream test. appstreamcli is missing.
-- Disabling debug info
CMake Warning (dev) at /usr/lib64/cmake/Qt5/Qt5ModuleLocation.cmake:4 (set):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '${_qt5_install_prefix}/Qt5@module@/Qt5@module@Config.cmake'

  the old evaluation rules produce:

    '/usr/lib64/cmake/Qt5/Qt5Config.cmake'

  but the new evaluation rules produce:

    '/usr/lib64/cmake/Qt5@module@/Qt5@module@Config.cmake'

  Using the old result for compatibility since the policy is not set.
Call Stack (most recent call first):
  /usr/lib64/cmake/Qt5/Qt5Config.cmake:25 (include)
  liblattedock/CMakeLists.txt:4 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found KF5: success (found version "5.30.0") found components:  WindowSystem CoreAddons Plasma PlasmaQuick IconThemes 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jason/programs/git/Latte-Dock/build
[  0%] Built target translations-containment
[  0%] Built target translations-plasmoid
[  0%] Built target translations-app
[  4%] Automatic moc for target latte-dock
[  4%] Built target latte-dock_automoc
[ 66%] Built target latte-dock
[ 71%] Automatic moc for target lattedockplugin
[ 71%] Built target lattedockplugin_automoc
[100%] Built target lattedockplugin
[  0%] Built target translations-containment
[  0%] Built target translations-plasmoid
[  0%] Built target translations-app
[  4%] Automatic moc for target latte-dock
[  4%] Built target latte-dock_automoc
[ 66%] Built target latte-dock
[ 71%] Automatic moc for target lattedockplugin
[ 71%] Built target lattedockplugin_automoc
[100%] Built target lattedockplugin
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/share/locale/de/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/el/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/es/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/it/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/pl/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/zh_TW/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/de/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/el/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/es/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/it/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/pl/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/ro/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/zh_TW/LC_MESSAGES/latte-dock.mo
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/metadata.desktop
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/AppletItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/ConfigOverlay.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/PanelBox.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/VisibilityManager.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/EditModeVisual.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/AddWidgetVisual.qml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/images
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/images/panel-west.png
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/code
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/code/LayoutManager.js
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/splitter2.png
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/splitter.png
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/blueprint.jpg
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/config
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/config/main.xml
-- Installing: /usr/share/metainfo/org.kde.latte.containment.appdata.xml
-- Installing: /usr/share/kservices5/plasma-applet-org.kde.latte.containment.desktop
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/metadata.desktop
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ConfigAppearance.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskWindows.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/GlowPoint.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipDelegate.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ConfigPanel.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipWindowMouseArea.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskGroupItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/main.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/VisualAddItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskIconItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/MouseHandler.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskDelegate.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ConfigInteraction.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskIconBuffers.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskActiveItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskProgressOverlay.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/CircleText.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ContextMenu.qml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/images
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/images/panel-west.png
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/tools.js
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/activitiesTools.js
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/layout.js
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/config
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/config/config.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/config/main.xml
-- Installing: /usr/share/metainfo/org.kde.latte.plasmoid.appdata.xml
-- Installing: /usr/share/kservices5/plasma-applet-org.kde.latte.plasmoid.desktop
-- Up-to-date: /usr/share/plasma/shells/org.kde.latte.shell
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/defaults
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/metadata.desktop
-- Up-to-date: /usr/share/plasma/shells/org.kde.latte.shell/contents
-- Up-to-date: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/config.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/TasksConfig.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/Header.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/AppearanceConfig.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/LatteDockConfiguration.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/LatteTextField.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/BehaviorConfig.qml
-- Up-to-date: /usr/share/plasma/shells/org.kde.latte.shell/contents/views
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/views/Panel.qml
-- Up-to-date: /usr/share/plasma/shells/org.kde.latte.shell/contents/controls
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/controls/SpinBox.qml
-- Up-to-date: /usr/share/plasma/shells/org.kde.latte.shell/contents/fonts
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/fonts/tangerine.ttf
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/fonts/SIL Open Font License.txt
-- Installing: /usr/share/metainfo/org.kde.latte.shell.appdata.xml
-- Installing: /usr/share/kservices5/plasma-shell-org.kde.latte.shell.desktop
-- Installing: /usr/bin/latte-dock
-- Installing: /usr/share/applications/latte-dock.desktop
-- Installing: /usr/lib/qt/qml/org/kde/latte/liblattedockplugin.so
-- Installing: /usr/lib/qt/qml/org/kde/latte/qmldir
-- Installing: /usr/share/icons/hicolor/16x16/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/22x22/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/24x24/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/32x32/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/48x48/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/scalable/apps/latte-dock.svg
-- Installing: /usr/share/icons/breeze/applets/256/org.kde.latte.plasmoid.svg
[jason@alfred Latte-Dock]$ latte-dock 
Segmentation fault (core dumped)
[jason@alfred Latte-Dock]$ 

`

**Comment by omni6** [comment]
do you have removed the old latte config files in your ~/.config ?

**Comment by audoban** [comment]
please run again but with debug. `latte-dock --debug`

**Comment by saltymedic** [comment]
Works now thanks. I forgot to add it as a widget. Here's the output from debug:

`
[jason@alfred Latte-Dock]$ latte-dock --debug
[debug 16:59:49.889889] - package is valid true
[debug 16:59:49.889889] - Latte::DockCorona the package QJsonObject({"KPlugin":{"Authors":[{"Email":"mvourlakos@gmail.com, audoban@openmailbox.org","Name":"Michail Vourlakos, Smith Ar"}],"Description":"Shell provided for the Latte Dock","Id":"org.kde.latte.shell","License":"GPLv3+","Name":"Latte Shell","ServiceTypes":["Plasma/Shell"],"Version":"0.5.91","Website":"https://github.com/psifidotos/Latte-Dock"},"Keywords":"shell","X-KDE-ParentApp":"latte-dock"}) is valid!
[debug 16:59:49.933933] - Adding dock for container...
[debug 16:59:50.239239] - SOURCE: QUrl("/usr/share/plasma/shells/org.kde.latte.shell/contents/views/Panel.qml")
[warning 16:59:50.272272] - Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
[warning 16:59:50.331331] - Failed to register unity service
[debug 16:59:50.469469] - ----------- Latte Plasmoid Signal: Activities number was changed ---------
[debug 16:59:50.469469] - 48a5a990-595a-452f-ba6d-c4af6f7d5dea
[debug 16:59:50.469469] - 421ebec6-f257-426c-b9f6-ab1967ecdac8
[debug 16:59:50.469469] - ----------- Latte Plasmoid Signal End ---------
[warning 16:59:50.490490] - Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
Segmentation fault (core dumped)
[jason@alfred Latte-Dock]$ 

`

**Comment by psifidotos** [comment]
@saltymedic I didnt understand, is this fixed for you with the proposed solutions?

**Comment by saltymedic** [comment]
Yes. It works. I had expected it to just launch. I forgot that it works as a plasma widget that I needed to add to the desktop. My mistake. Thank you

**Comment by psifidotos** [comment]
> Yes. It works. I had expected it to just launch. I forgot that it works as a plasma widget that I needed  to add to the desktop. My mistake. Thank you

no, it isnt your mistake... Latte provides a latte-dock executable that should just launch without adding anything in your desktop. If the above steps didnt fix the crash for you then we must investigate what is happening. The Latte plasmoid which is also provided in the same package and you can add it your desktop is mainly for testing purposes e.g. it can never be above windows...

**Comment by saltymedic** [comment]
I understand.

 Well it is not launching. From the command line I get a Segmentation Fault (core dumped). The only way I can get it to show up is as a plasmoid. What do you recommend I try next? Thanks

**Comment by psifidotos** [comment]
What is your graphics card? What plasma, kf5 and qt version are you using? what distro?

**Comment by saltymedic** [comment]
I'm running multi monitors (three) using two Gigabyte GeForce GTX 970's 

KDE Plasma 5.8.5
KDE Frameworks 5.30.0
Qt 5.8.0
Arch distro kernel 4.9.6-1

**Comment by psifidotos** [comment]
ok!!! multi-screen is not supported yet...
There is a chance that this is relevant with that...

**Comment by saltymedic** [comment]
Yes it could be the problem.
However, I did have it working week or two ago. When I tried updating from the latest Github it stopped.
Thanks

**Comment by psifidotos** [comment]
You could try to debug it if you want...

- Install ddd
-  ddd latte-dock
-  in ddd window write and execute, run
- when it crashes, click status from the menu, backtrace

This will show you a window with numbered lines, this coulb be helpful for us...

**Comment by saltymedic** [comment]
I'm not a programmer so this is my first time looking into this. I'm happy to help if you need a multi monitor test person. Here's the screen shot from following your directions.

From the terminal
![screenshot_20170201_172530](https://cloud.githubusercontent.com/assets/18824694/22532271/743f8c50-e8a3-11e6-82d9-9a31d0f284b6.png)

From ddd
![screenshot_20170201_172308](https://cloud.githubusercontent.com/assets/18824694/22532236/2fe36176-e8a3-11e6-843c-456b082be432.png)

**Comment by psifidotos** [comment]
Nice!!! We can fix that!!!! It looks like a call for resizing the dock window before the screen has been set correctly! I will try something tomorrow to test if you want!

For a not programmer this went great and very fast!!! Thank u !!!

**Comment by psifidotos** [comment]
Could you please try branch fix116 ?

**Comment by psifidotos** [comment]
I merged the fix also to master... I hope we passed that crash...

**Comment by saltymedic** [comment]
There is some progress, thanks

When I launch, it flickered back and forth between screen 1 and 2 eventually settling on screen 1. Then I can not interact with the dock. Latte-dock then uses 25% of my CPU. CPU is an Intel i7-4970

Jason

**Comment by psifidotos** [comment]
Can you check if this is a multi-screen issue?

If you close latte, enable one one monitor and run latte it behaves the same?

also,
if you run latte-dock --debug what is the output in such case?

**Comment by saltymedic** [comment]
I disabled 2 of the 3 monitors and it seems to work fine. Here is the --debug output from that test

`
[jason@alfred Latte-Dock]$ latte-dock --debug
[debug 15:25:56.108108] - package is valid true
[debug 15:25:56.108108] - Latte::DockCorona the package QJsonObject({"KPlugin":{"Authors":[{"Email":"mvourlakos@gmail.com, audoban@openmailbox.org","Name":"Michail Vourlakos, Smith Ar"}],"Description":"Shell provided for the Latte Dock","Id":"org.kde.latte.shell","License":"GPLv3+","Name":"Latte Shell","ServiceTypes":["Plasma/Shell"],"Version":"0.5.91","Website":"https://github.com/psifidotos/Latte-Dock"},"Keywords":"shell","X-KDE-ParentApp":"latte-dock"}) is valid!
[debug 15:25:56.151151] - Adding dock for container...
[debug 15:25:56.303303] - SOURCE: QUrl("/usr/share/plasma/shells/org.kde.latte.shell/contents/views/Panel.qml")
[warning 15:25:56.339339] - Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
[warning 15:25:56.482482] - Failed to register unity service
[debug 15:25:56.608608] - ----------- Latte Plasmoid Signal: Activities number was changed ---------
[debug 15:25:56.608608] - 48a5a990-595a-452f-ba6d-c4af6f7d5dea
[debug 15:25:56.608608] - 421ebec6-f257-426c-b9f6-ab1967ecdac8
[debug 15:25:56.608608] - ----------- Latte Plasmoid Signal End ---------
[warning 15:25:56.629629] - Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
[warning 15:25:56.753753] - file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/PanelBox.qml:156: TypeError: Cannot read property 'enabledBorders' of null
`

After that I enabled all three monitors and it still does not work.

Jason

**Comment by psifidotos** [comment]
@saltymedic the output looks ok... so this is a three monitors issue...

**Comment by psifidotos** [comment]
@saltymedic can we play with this case? I have uploaded a branch called **3crash** can you test it if the problem persists and comment what is the behavior? 

and I would like to see please your file:   .config/latte-dock-appletsrc

**Comment by saltymedic** [comment]
I tried the 3crash branch and I didn't see much improved behavior.

CPU still at 25%, flashing of the dock between screens 1&2 (left and middle, middle set as primary). I still can not interact with the menu. At times it makes the rest of the desktop environment unresponsive, but the mouse cursor still moves.

Contents of my .config file:
`
[ActionPlugins][1]
RightButton;NoModifier=org.kde.contextmenu

[Containments][1]
activityId=
formfactor=2
immutability=1
lastScreen=0
location=4
plugin=org.kde.latte.containment
timerHide=700
timerShow=200
visibility=2
wallpaperplugin=org.kde.image

[Containments][1][Applets][2]
immutability=1
plugin=org.kde.latte.plasmoid

[Containments][1][Applets][2][Configuration][General]
isInNowDockPanel=true
launchers=multi

[Containments][1][Applets][3]
immutability=1
plugin=org.kde.plasma.analogclock

[Containments][1][General]
appletOrder=2;3


`
![screenshot_20170207_220008](https://cloud.githubusercontent.com/assets/18824694/22724053/dc168090-ed80-11e6-93cc-a045bec413ff.png)

Screen video capture of behavior
https://youtu.be/QPSYz6NX6GI

**Comment by psifidotos** [comment]
From the video what i understand is that latte has stuck in a screen changing loop!!! Can you please check if you set as primary screen the first one does this still happen?

**Comment by psifidotos** [comment]
there is a chance that the branch **primary** fixes this...
The goal is to show the latte dock in your primary screen without having any further issues...

please let me know for the output of this...

**Comment by saltymedic** [comment]
hmmmm

I'm sorry but I'm afraid I don't know what I'm doing

I thought I knew how to use git for the branches, but I'm new at this and I don't know what branch I am getting now. I am using Gitkraken. I don't know if what I am getting or building is from the master branch or primary.

Any hints?

Thanks

Jason

**Comment by psifidotos** [comment]
Personally i use git directly so only thing I can do is to guide you through this, you can go with command line to the root of Latte, that is the directory containing **_install.sh_** file

executing in it:
`git status` ,prints infos and one of them is the current branch you are in
`git checkout primary` ,I dont know if gitkraken has downloaded the primary branch if it does then this command will get you into the primary branch otherwise a message saying that primary branch does not exist will be print

if it doesnt exist then you can execute:
`git checkout -b primary origin/primary` , this command downloads primary branch in your system and gets you in it. So you can just check with `git status` if you are in primary branch and if you are then you can just execute: `sh install.sh` in order to install latte based on the primary branch

in order to return to the master branch you can type:
`git checkout master` and install latte again through `sh install.sh` in order to have the master branch version installed

**Comment by saltymedic** [comment]
Sorry for not getting back to you sooner.

Thank you so much for providing the instructions for me as well as the fix.

It seems to work just fine now. Is there anything you want me to test with it?

Thank you

Jason

**Comment by psifidotos** [comment]
> Is there anything you want me to test with it?

I have just merge the half patch in master. Can you please check if it still works ok for the master branch?

**Comment by saltymedic** [comment]
Now it is not launching:
`
[jason@alfred Latte-Dock]$ latte-dock --debug
[debug 21:11:12.202202] - package is valid true
[debug 21:11:12.203203] - Latte::DockCorona the package QJsonObject({"KPlugin":{"Authors":[{"Email":"mvourlakos@gmail.com, audoban@openmailbox.org","Name":"Michail Vourlakos, Smith Ar"}],"Description":"Shell provided for the Latte Dock","Icon":"latte-dock","Id":"org.kde.latte.shell","License":"GPLv3+","Name":"Latte Shell","ServiceTypes":["Plasma/Shell"],"Version":"0.5.91","Website":"https://github.com/psifidotos/Latte-Dock"},"Keywords":"shell","X-KDE-ParentApp":"latte-dock"}) is valid!
[debug 21:11:12.246246] - Adding dock for container...
[debug 21:11:12.568568] - SOURCE: QUrl("/usr/share/plasma/shells/org.kde.latte.shell/contents/views/Panel.qml")
[warning 21:11:12.616616] - Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
[warning 21:11:12.635635] - Failed to register unity service
[debug 21:11:12.813813] - ----------- Latte Plasmoid Signal: Activities number was changed ---------
[debug 21:11:12.813813] - 48a5a990-595a-452f-ba6d-c4af6f7d5dea
[debug 21:11:12.813813] - 421ebec6-f257-426c-b9f6-ab1967ecdac8
[debug 21:11:12.813813] - ----------- Latte Plasmoid Signal End ---------
[warning 21:11:12.835835] - Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
[warning 21:11:12.896896] - file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml:1157: TypeError: Cannot read property 'visibility' of null
[warning 21:11:12.896896] - file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml:1140: TypeError: Cannot read property 'visibility' of null
Segmentation fault (core dumped)
[jason@alfred Latte-Dock]$ 

`

![spectacle y31204](https://cloud.githubusercontent.com/assets/18824694/22859612/b96f44ca-f09e-11e6-94af-990d37aa1799.png)

**Comment by psifidotos** [comment]
we are near :), a little patience more... :)

@saltymedic can you please test branch **primary2** it should fix this crash!

**Comment by psifidotos** [comment]
@saltymedic forget the **primary2** branch... I made some commits in **master** that may have fixed this all issue... Give it a try...

**Comment by saltymedic** [comment]
Still not launching:

`
[jason@alfred Latte-Dock]$ latte-dock --debug
[debug 20:17:44.704704] - package is valid true
[debug 20:17:44.704704] - Latte::DockCorona the package QJsonObject({"KPlugin":{"Authors":[{"Email":"mvourlakos@gmail.com, audoban@openmailbox.org","Name":"Michail Vourlakos, Smith Ar"}],"Description":"Shell provided for the Latte Dock","Icon":"latte-dock","Id":"org.kde.latte.shell","License":"GPLv3+","Name":"Latte Shell","ServiceTypes":["Plasma/Shell"],"Version":"0.5.91","Website":"https://github.com/psifidotos/Latte-Dock"},"Keywords":"shell","X-KDE-ParentApp":"latte-dock"}) is valid!
[debug 20:17:44.748748] - Adding dock for container...
[debug 20:17:44.908908] - SOURCE: QUrl("/usr/share/plasma/shells/org.kde.latte.shell/contents/views/Panel.qml")
[warning 20:17:44.962962] - Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
[warning 20:17:44.986986] - Failed to register unity service
[debug 20:17:45.122122] - ----------- Latte Plasmoid Signal: Activities number was changed ---------
[debug 20:17:45.122122] - 48a5a990-595a-452f-ba6d-c4af6f7d5dea
[debug 20:17:45.122122] - 421ebec6-f257-426c-b9f6-ab1967ecdac8
[debug 20:17:45.122122] - ----------- Latte Plasmoid Signal End ---------
[warning 20:17:45.145145] - Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
[warning 20:17:45.208208] - file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml:1157: TypeError: Cannot read property 'visibility' of null
[warning 20:17:45.208208] - file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml:1140: TypeError: Cannot read property 'visibility' of null
Segmentation fault (core dumped)
[jason@alfred Latte-Dock]$ 

`
![spectacle m12555](https://cloud.githubusercontent.com/assets/18824694/22869977/aa8b01b6-f160-11e6-9764-965b9dc4e6f2.png)

**Comment by psifidotos** [comment]
Are you sure you updated master with the latest commits?

**Comment by DemaroStanberry** [comment]
I also have a 3 monitor setup and the experience is similar to what @saltymedic described when built using commit 7e1475d901702d2d99d0e048b73da99a4305a6c3

**Comment by psifidotos** [comment]
@DemaroStanberry can you please check branch primary2 if it has a different behavior?

**Comment by DemaroStanberry** [comment]
$ mv ~/.config/lattedock-appletsrc ~/.config/lattedock-appletsrc-bkp
$ latte-dock --debug
`[debug 11:33:06.582582] - package is valid true
[debug 11:33:06.582582] - Latte::DockCorona the package QJsonObject({"KPlugin":{"Authors":[{"Email":"mvourlakos@gmail.com, audoban@openmailbox.org","Name":"Michail Vourlakos, Smith Ar"}],"Description":"Shell provided for the Latte Dock","Icon":"latte-dock","Id":"org.kde.latte.shell","License":"GPLv3+","Name":"Latte Shell","ServiceTypes":["Plasma/Shell"],"Version":"0.5.91","Website":"https://github.com/psifidotos/Latte-Dock"},"Keywords":"shell","X-KDE-ParentApp":"latte-dock"}) is valid!
[debug 11:33:06.584584] - loading default layout
[debug 11:33:06.627627] - Adding dock for container...
[debug 11:33:06.842842] - SOURCE: QUrl("/usr/share/plasma/shells/org.kde.latte.shell/contents/views/Panel.qml")
[warning 11:33:07.310310] - file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml:1157: TypeError: Cannot read property 'visibility' of null
[warning 11:33:07.310310] - file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml:1140: TypeError: Cannot read property 'visibility' of null
[warning 11:33:07.684684] - Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
[warning 11:33:07.689689] - file:///usr/lib64/qt5/qml/QtQuick/Controls/Button.qml:99: TypeError: Cannot read property of null
[debug 11:33:07.750750] - ----------- Latte Plasmoid Signal: Activities number was changed ---------
[debug 11:33:07.750750] - c484648c-be32-4994-aa4d-7e68ee6f05da
[warning 11:33:07.750750] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/activitiesTools.js:182: TypeError: Cannot read property 'length' of undefined
[warning 11:33:08.396396] - Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
[warning 11:33:08.396396] - file:///usr/share/plasma/plasmoids/org.kde.plasma.analogclock/contents/ui/analogclock.qml:46: TypeError: Cannot read property 'DateTime' of undefined
[warning 11:33:08.396396] - file:///usr/share/plasma/plasmoids/org.kde.plasma.analogclock/contents/ui/analogclock.qml:47: TypeError: Cannot read property 'DateTime' of undefined
Segmentation fault
`

**Comment by psifidotos** [comment]
Can you check if it is the same crash? 

You could try to debug it if you want...

- Install ddd
- ddd latte-dock
- in ddd window write and execute, run
- when it crashes, click status from the menu, backtrace

This will show you a window with numbered lines, this could be helpful for us...

**Comment by DemaroStanberry** [comment]
Using branch primary2

![screenshot_20170213_120837](https://cloud.githubusercontent.com/assets/22458241/22896299/33d90204-f1e5-11e6-87aa-123dc36539c7.png)

**Comment by psifidotos** [comment]
@DemaroStanberry can you please test also the new commit in primary2 ?

**Comment by DemaroStanberry** [comment]
Results in the same behaviour. Not sure if this changes anything but I have KF5 v5.31 and Plasma 5.9.1 installed if that helps any.

**Comment by psifidotos** [comment]
if they have updated the ContainmentView for kf5 v5.31 then this would make sense...

when it is available in opensuse I will check it!!

**Comment by psifidotos** [comment]
when it hasnt been updated for over a year...
 
can you chat in irc ?

**Comment by psifidotos** [comment]
I am at #latte-dock channel at irc.freenode.net

**Comment by DemaroStanberry** [comment]
![screenshot_20170213_133804](https://cloud.githubusercontent.com/assets/22458241/22899792/b074c396-f1f1-11e6-9fc4-0a2113aea913.png)

**Comment by DemaroStanberry** [comment]
![screenshot_20170213_134834](https://cloud.githubusercontent.com/assets/22458241/22900218/243b78fa-f1f3-11e6-8544-90b5930847d3.png)

**Comment by psifidotos** [comment]
@audoban the crash was related to QueuedConnection for adaptToScreen slot...

**Comment by psifidotos** [comment]
@saltymedic @DemaroStanberry can we have a screenshot of the current state of this? I think we fixed the crash in master branch but still there isnt a latte  dock on primary screen working correctly, right ?

**Comment by DemaroStanberry** [comment]
You may need to zoom in 1:1 to see the  graphic at the bottom of screenshot.
![latte-graphic](https://cloud.githubusercontent.com/assets/22458241/22903127/2d8d9d02-f1fd-11e6-89c1-665fb4a27d39.png)

Below is a visual of how kde enumerates screens where screen 1(Primary) is middle, screen 2 is on the left and screen 3 is on the right
![kde_screens](https://cloud.githubusercontent.com/assets/22458241/22903327/dd4d5d18-f1fd-11e6-9edb-f9b37fd2f3a9.png)

**Comment by psifidotos** [comment]
@DemaroStanberry  can you right click on that small space? does the Latte configuration window appears?

**Comment by DemaroStanberry** [comment]
@psifidotos I'm unable to interact with Latte.

**Comment by psifidotos** [comment]
Is Latte going from screen to screen or it stands in a specific screen without doing anything?

**Comment by DemaroStanberry** [comment]
It remains on that screen.

**Comment by psifidotos** [comment]
@DemaroStanberry as long it doesnt crash any more you could try:

latte-dock --debug --with-window --graphics --mask

this should give us messages both in the command line but also a window with all the important variables of Latte...

please publish here the text messages and a screenshot of Latte Debug Window

**Comment by DemaroStanberry** [comment]
![screen](https://cloud.githubusercontent.com/assets/22458241/22942054/83ebb17e-f2ad-11e6-993d-2397a616f978.png)

`[debug 12:04:11.910910] - package is valid true`
`[debug 12:04:11.910910] - Latte::DockCorona the package QJsonObject({"KPlugin":{"Authors":[{"Email":"mvourlakos@gmail.com, audoban@openmailbox.org","Name":"Michail Vourlakos, Smith Ar"}],"Description":"Shell provided for the Latte Dock","Icon":"latte-dock","Id":"org.kde.latte.shell","License":"GPLv3+","Name":"Latte Shell","ServiceTypes":["Plasma/Shell"],"Version":"0.5.91","Website":"https://github.com/psifidotos/Latte-Dock"},"Keywords":"shell","X-KDE-ParentApp":"latte-dock"}) is valid!`
`[debug 12:04:11.912912] - loading default layout`
`[debug 12:04:11.949949] - Adding dock for container...`
`[debug 12:04:12.169169] - SOURCE: QUrl("/usr/share/plasma/shells/org.kde.latte.shell/contents/views/Panel.qml")`
`[warning 12:04:12.652652] - file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml:1157: TypeError: Cannot read property 'visibility' of null`
`[warning 12:04:12.652652] - file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml:1140: TypeError: Cannot read property 'visibility' of null`
`[debug 12:04:12.694694] - 0, 0, 0, true`
`[debug 12:04:12.694694] - normal state changed to:true`
`[warning 12:04:13.131131] - Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)`
`[warning 12:04:13.138138] - file:///usr/lib64/qt5/qml/QtQuick/Controls/Button.qml:99: TypeError: Cannot read property of null`
`[debug 12:04:13.226226] - ----------- Latte Plasmoid Signal: Activities number was changed ---------`
`[debug 12:04:13.226226] - c484648c-be32-4994-aa4d-7e68ee6f05da`
`[warning 12:04:13.226226] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/activitiesTools.js:182: TypeError: Cannot read property 'length' of undefined`
`[debug 12:04:13.432432] - 0, 0, 0, true`
`[debug 12:04:13.504504] - 0, 0, 0, true`
`[warning 12:04:13.693693] - Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion`
`[warning 12:04:13.693693] - file:///usr/share/plasma/plasmoids/org.kde.plasma.analogclock/contents/ui/analogclock.qml:46: TypeError: Cannot read property 'DateTime' of undefined`
`[warning 12:04:13.693693] - file:///usr/share/plasma/plasmoids/org.kde.plasma.analogclock/contents/ui/analogclock.qml:47: TypeError: Cannot read property 'DateTime' of undefined`
`[debug 12:04:14.33] - 0, 0, 0, true`
`[debug 12:04:14.33] - 0, 0, 0, true`
`[debug 12:04:14.33] - 0, 0, 0, true`
`[debug 12:04:14.2828] - 0, 1, 0, true`
`[debug 12:04:14.9898] - 0, 1, 0, true`
`[debug 12:04:14.9898] - 0, 1, 0, true`
`[debug 12:04:14.9898] - 0, 1, 0, true`
`[debug 12:04:14.9999] - 0, 1, 0, true`
`[debug 12:04:14.9999] - 0, 1, 0, true`
`[debug 12:04:14.9999] - 0, 1, 0, true`
`...`

**Comment by psifidotos** [comment]
the messages stop there or continue ??

**Comment by DemaroStanberry** [comment]
it continues on with `[debug <timestamp>] - 0, 1, 0, true`

**Comment by psifidotos** [comment]
ok... one more thing... the debug window can grow more in height... can you please make one more screenshot that shows all the window contents ?

**Comment by DemaroStanberry** [comment]
![screen2](https://cloud.githubusercontent.com/assets/22458241/22942903/0a67c17c-f2b1-11e6-914e-256d87497407.png)

**Comment by psifidotos** [comment]
ok.... please test again with the new master... I have improved a bit the debug window, so the unknown values should at least show us what are these values and also I added a containsmouse...

so please try that:
1. close Latte and remove the lattedock-appletsrc
2. install Latte from master branch with the new commit
3. take a screenshot for the new debug window just like the one you sent
4. check when the mouse goes insided the latte dock, that is the green line at the bottom for you if the new flag in the debug window, Contains Mouse becomes yes...

thanks again...

**Comment by psifidotos** [comment]
oh... and upload here the new lattedock-appletsrc to give it a check...

**Comment by DemaroStanberry** [comment]
Cursor outside latte container..
![before](https://cloud.githubusercontent.com/assets/22458241/22950002/c31f2a26-f2c9-11e6-9ccd-e7bd9ee743e4.png)

Cursor hovering over latte..
![after](https://cloud.githubusercontent.com/assets/22458241/22950011/c67c6f12-f2c9-11e6-9fbe-3da7624e91ef.png)

config file..

[ActionPlugins][1]
RightButton;NoModifier=org.kde.contextmenu

[Containments][1]
activityId=
formfactor=2
immutability=1
lastScreen=0
location=4
plugin=org.kde.latte.containment
wallpaperplugin=org.kde.image

[Containments][1][Applets][2]
immutability=1
plugin=org.kde.latte.plasmoid

[Containments][1][Applets][2][Configuration][General]
isInLatteDock=true

[Containments][1][Applets][3]
immutability=1
plugin=org.kde.plasma.analogclock

[Containments][1][General]
appletOrder=2;3

**Comment by psifidotos** [comment]
ok... the configuration is ok... but I dont like the values in the debug window... especially the:
**Visibility:none**

can you please test branch fix116 and upload a screenshot of the debug window?

**Comment by DemaroStanberry** [comment]
Ok.. a lot of screenshots: 
1. Three monitor setup which shows latte on left display
2. same monitor setup but now latte is on the primary display (it's actually moving between the two displays)
3. Debug window with mouse outside latte region
4. Debug window with mouse hover over latte region
5. Debug window with mouse right-click inside latte region

![a](https://cloud.githubusercontent.com/assets/22458241/22952684/9d0e7ada-f2d3-11e6-83d4-de235019261f.png)
![b](https://cloud.githubusercontent.com/assets/22458241/22952686/a02424fe-f2d3-11e6-8433-bb52ab67ba10.png)
![c](https://cloud.githubusercontent.com/assets/22458241/22952691/a4f13864-f2d3-11e6-830a-8946b07caf04.png)
![d](https://cloud.githubusercontent.com/assets/22458241/22952698/aa8a329e-f2d3-11e6-87ca-6ec4c6046b6e.png)
![e](https://cloud.githubusercontent.com/assets/22458241/22952702/ad886344-f2d3-11e6-98de-43da1d665e49.png)

**Comment by psifidotos** [comment]
the main issue is that latte doesnt stand in one screen, so latte propably doesnot load correctly... this can be fixed but we need to schedule an irc meeting. @DemaroStanberry do you think we can schedule this today?

**Comment by psifidotos** [comment]
@DemaroStanberry also you can checkout this new commit in fix116 branch... there is a chance to fix this crazy behavior for the dock not sitting in just one screen

**Comment by DemaroStanberry** [comment]
We can set one up today if the offer still stands.

**Comment by psifidotos** [comment]
@DemaroStanberry ok... are you available between 18:30 - 20:00 Greece time ?

**Comment by DemaroStanberry** [comment]
works for me

**Comment by psifidotos** [comment]
ok... so the last fix works for you???

**Comment by DemaroStanberry** [comment]
commit f914af806d5d8adc7f5dbdb12eb11c40ab9d3868 didn't fix the plasmoid jumping between screens

**Comment by psifidotos** [comment]
> ok... so the last fix works for you???

what do you mean then?

**Comment by psifidotos** [comment]
> works for me

ok... so what do you mean it works for you?

**Comment by DemaroStanberry** [comment]
I meant that the proposed time to chat on IRC 'works for me'

**Comment by psifidotos** [comment]
ok ok

I am already there...

**Comment by DemaroStanberry** [comment]
![1](https://cloud.githubusercontent.com/assets/22458241/23032620/a6b58372-f43a-11e6-9ad0-966274b58f64.png)

**Comment by DemaroStanberry** [comment]
![2](https://cloud.githubusercontent.com/assets/22458241/23032886/b1b84966-f43b-11e6-87d2-2ee2fb1a9b7d.png)

**Comment by psifidotos** [comment]
this is a nightmare... I can only fix this when the multi-screen codebase will land in Latte...

**Comment by psifidotos** [comment]
@saltymedic @DemaroStanberry 

:) from the era of multi screens... I think this is fixed... you could try the **multiscreens** branch to test it... multi screens is at its first steps, to except to be able to set the dock screen yet... but at least will be always at your primary screen and latte shouldnt crash...

**Comment by saltymedic** [comment]
Seems to be working. Thanks!

**Comment by psifidotos** [comment]
did you use the master branch?

**Comment by DemaroStanberry** [comment]
It's fixed in the master branch

**Comment by saltymedic** [comment]
Yes

**Comment by psifidotos** [comment]
nice!! how do you find it?
