### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#132]
In visibility mode auto -hide and when the dock rise up....
Sometimes, I see something like this:
![screenshot_20170204_122328](https://cloud.githubusercontent.com/assets/24593950/22618122/43503764-ead5-11e6-9eb6-141bbd907b2e.png)

**Comment by audoban** [comment]
It is KWin's responsibility to clean the mask from a window, I would not know if we could avoid this defect.

**Comment by psifidotos** [comment]
This problem is not appearing in all cases...
I have a laptop that this is not appearing...

As a debugging I disabled mask completely and used the whole window area for the animations... Painting glitches were still appearing in my main system... This must be up in the stack, wayland may fix it of course but I dont know when we will be able to support wayland... :)

**Comment by JenaPlinsky** [comment]
Do you think that with wayland, screen rendering will be better and will solve this kind of problem ?

**Comment by psifidotos** [comment]
wayland fixes all the rendering issues for painting but i will send also a question to kwin developers to confirm it

**Comment by psifidotos** [comment]
KDE Bug ID: https://bugs.kde.org/show_bug.cgi?id=376593

**Comment by psifidotos** [comment]
just as a comment this happens in my system also in restoring zoom that nothing has to do with masking. So there is a big chance that this is related totally at X painting or that the graphic card can not catch up...

**Comment by JenaPlinsky** [comment]
Great, well done
Wayland was born precisely why I believe

**Comment by psifidotos** [comment]
ok... confirmed also from kwin developers... this is an X11 bug in Shape extension...

> The Qt documentation does not make much sense for X11. The mask uses the shape extension https://www.x.org/releases/current/doc/xextproto/shape.html
> The compositor has not much to do with it. You can easily see this by using common shaped windows such as xeyes.

**Comment by JenaPlinsky** [comment]
Here's an **Real** screenshot in debug mode. maybe it can be useful
![vlcsnap-2017-02-19-12h56m41s147](https://cloud.githubusercontent.com/assets/24593950/23102179/b2cee92a-f6a4-11e6-924d-4d86739b558c.png)

**Comment by psifidotos** [comment]
Execute xeyes application... you will see that when the eyes are moving the rendering isnt good... Martin from kwin tagged it as a known issue with X Shape

**Comment by psifidotos** [comment]
@JenaPlinsky can you please test branch **buffers** ? There is the chance that painting for increasing the mask cases will be better... Can you reproduce the last screenshot based on the **buffers** branch ?

**Comment by JenaPlinsky** [comment]
there is no Buffer banch

**Comment by psifidotos** [comment]
yes there isnt... I already merged it in master

**Comment by JenaPlinsky** [comment]
I can confirm that from the master branch, the problem mentioned above **is still present**

**Comment by psifidotos** [comment]
> I can confirm that from the master branch, the problem mentioned above is still present

only thing can be done then, is to wait for wayland...

**Comment by JenaPlinsky** [comment]
@psifidotos  i'm wrong or this kind of problem has been greatly reduced?

**Comment by psifidotos** [comment]
maybe the last commits improved a bit the situation... on the wayland side when I am trying Latte in wayland this problem doesnt exist at all..

**Comment by JenaPlinsky** [comment]
Great !!!, this is a fantastic news 👍
